# Generated by Django 5.2.17 on 2026-08-07 16:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('actions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField()),
                ('agenda', models.TextField(blank=True)),
                ('rules', models.TextField(blank=True)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='events/banners/')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('venue', models.CharField(max_length=250)),
                ('organizer', models.CharField(blank=True, max_length=150)),
                ('coordinator', models.CharField(blank=True, max_length=150)),
                ('max_participants', models.PositiveIntegerField(default=100)),
                ('registration_deadline', models.DateField(blank=True, null=True)),
                ('category', models.CharField(choices=[('plantation', 'Tree Plantation'), ('clean', 'Clean Campus'), ('awareness', 'Awareness Campaign'), ('workshop', 'Workshop'), ('seminar', 'Seminar'), ('competition', 'Competition'), ('community', 'Community Outreach'), ('celebration', 'Celebration'), ('other', 'Other')], default='other', max_length=20)),
                ('is_past', models.BooleanField(default=False)),
                ('impact_text', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sdgs', models.ManyToManyField(blank=True, related_name='events', to='actions.sdg')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(blank=True, max_length=40, unique=True)),
                ('verification_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('register_number', models.CharField(blank=True, max_length=30)),
                ('issued_on', models.DateField(default=django.utils.timezone.localdate)),
                ('is_verified', models.BooleanField(default=False)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='accounts.studentprofile')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='events.event')),
            ],
            options={
                'ordering': ['-issued_on'],
            },
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('register_number', models.CharField(max_length=30)),
                ('attended_on', models.DateField(default=django.utils.timezone.localdate)),
                ('points_awarded', models.PositiveIntegerField(default=0)),
                ('has_certificate', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='events.event')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participations', to='accounts.studentprofile')),
            ],
            options={
                'ordering': ['-attended_on'],
                'constraints': [models.UniqueConstraint(fields=('event', 'register_number'), name='unique_event_participant')],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('register_number', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=120)),
                ('year', models.CharField(blank=True, max_length=5)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('gender', models.CharField(blank=True, max_length=1)),
                ('college', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField(blank=True)),
                ('registration_id', models.CharField(blank=True, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('waitlist', 'Waitlist'), ('cancelled', 'Cancelled')], default='confirmed', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('event', 'register_number'), name='unique_event_register_number')],
            },
        ),
    ]
