# Generated by Django 5.2.17 on 2026-08-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
