# Generated by Django 5.2.17 on 2026-08-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_eventregistration_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('tech_workshop', 'Technical Workshop'), ('hackathon', 'Hackathon'), ('seminar', 'Technical Seminar'), ('competition', 'Technical Competition'), ('ai', 'AI & Machine Learning'), ('iot', 'IoT & Smart Solutions'), ('robotics', 'Robotics'), ('sustainability', 'Sustainability Technology'), ('awareness', 'Environmental Awareness'), ('community', 'Community Outreach'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
