# Generated by Django 5.2.17 on 2026-08-07 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('event', 'Event'), ('registration', 'Registration'), ('competition', 'Competition'), ('result', 'Results'), ('notice', 'Notice'), ('volunteer', 'Volunteer Opportunity')], default='notice', max_length=20)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, max_length=270, unique=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('author', models.CharField(blank=True, max_length=150)),
                ('content', models.TextField()),
                ('excerpt', models.CharField(blank=True, max_length=400)),
                ('category', models.CharField(choices=[('environment', 'Environment'), ('climate', 'Climate'), ('sustainability', 'Sustainability'), ('campus', 'Campus'), ('sdgs', 'SDGs'), ('activities', 'Student Activities')], default='environment', max_length=20)),
                ('tags', models.CharField(blank=True, max_length=300)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=250)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=70, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Gallery categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImpactStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('trees', 'Trees Planted'), ('waste', 'Waste Collected (kg)'), ('water', 'Water Saved (litres)'), ('volunteers', 'Volunteers'), ('students', 'Students Reached'), ('campaigns', 'Campaigns Conducted'), ('events', 'Events Conducted'), ('members', 'Total Members')], max_length=20, unique=True)),
                ('value', models.PositiveIntegerField(default=0)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('icon', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'ordering': ['metric'],
            },
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='memories/')),
                ('year', models.PositiveSmallIntegerField(default=2026)),
                ('date', models.DateField(blank=True, null=True)),
                ('participants', models.PositiveIntegerField(default=0)),
                ('is_highlight', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-year', '-date'],
            },
        ),
        migrations.CreateModel(
            name='SDG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('short_name', models.CharField(blank=True, max_length=60)),
                ('description', models.TextField(blank=True)),
                ('contribution', models.TextField(blank=True, help_text='Eco Club contribution to this SDG')),
                ('icon', models.CharField(blank=True, help_text='Material icon name e.g. eco, water_drop, energy_savings_leaf', max_length=20)),
                ('color', models.CharField(default='#4CAF50', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='SDGActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('faculty', 'Faculty Coordinator'), ('student_coordinator', 'Student Coordinator'), ('executive', 'Executive Member')], max_length=25)),
                ('name', models.CharField(max_length=150)),
                ('position', models.CharField(blank=True, max_length=150)),
                ('designation', models.CharField(blank=True, max_length=150)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('year', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['role', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(default='logo', max_length=30)),
                ('name', models.CharField(max_length=120)),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=60, unique=True)),
                ('value', models.TextField(blank=True)),
                ('label', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='actions.gallerycategory')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
