# Generated by Django 5.2.17 on 2026-08-07 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actions', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery', to='events.event'),
        ),
        migrations.AddField(
            model_name='memory',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memories', to='events.event'),
        ),
        migrations.AddField(
            model_name='sdgactivity',
            name='sdg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='actions.sdg'),
        ),
    ]
